package gcu.backend.classroomservice.model;

import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Data;

// "Like", MongoDB Collection, used to store the like information
// @Data, automatically generate Getter, Setter, toString, Constructor
// @Document, used to specify the name of the collection
@Data
@Document(collection = "like")
public class Like {

    // Field '_id', type 'ObjectId'
    // Default value is generated by MongoDB
    @Id
    private ObjectId _id; // MongoDB에서 자동으로 생성되는 필드

    // Field 'email', type 'String'
    // This value is the email of a user who likes classroom
    private String email;

    // Field '호', type 'String'
    // This var is 호 a uswer likes classroom with
    private String 호;
}
